export const doseUnitList = [
  { name: 'g' },
  { name: 'mg' },
  { name: 'ml' },
  { name: 'ug' },
  { name: '板' },
  { name: '小包' },
  { name: '小袋' },
  { name: '粒' },
  { name: '片' },
  { name: '枚' },
  { name: '张' },
  { name: '贴' },
  { name: '支' },
  { name: '只' },
  { name: '饼' },
  { name: '袋' },
  { name: '盒' },
  { name: '桶' },
  { name: '单位' },
  { name: '万单位' },
  { name: '把' },
  { name: '%' }
]